# Generated by Django 5.2.6 on 2025-10-07 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssr_inDb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='drug',
            table='ssr_inDb_drug',
        ),
        migrations.AlterModelTable(
            name='druginorder',
            table='ssr_inDb_druginorder',
        ),
        migrations.AlterModelTable(
            name='order',
            table='ssr_inDb_order',
        ),
    ]
