# Generated by Django 5.2.6 on 2025-10-08 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssr_inDb', '0002_alter_drug_table_alter_druginorder_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='formation_datetime',
        ),
    ]
