# Generated by Django 5.2.6 on 2025-10-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssr_inDb', '0003_remove_order_formation_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ampoules_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество ампул'),
        ),
        migrations.AlterField(
            model_name='order',
            name='patient_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Масса пациента (кг)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='solvent_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Объём растворителя (мл)'),
        ),
    ]
