# Generated by Django 5.2.6 on 2025-10-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssr_inDb', '0001_initial_squashed_0008_alter_druginorder_drug_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='formation_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата формирования'),
        ),
    ]
