# Generated by Django 5.2.7 on 2025-11-28 10:51

import django.db.models.deletion
from django.db import migrations, models

from ._backup_data import restore_from_backup


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Показания')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL изображения')),
                ('concentration', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Концентрация (мг/мл)')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Объём ампулы (мл)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Препарат',
                'verbose_name_plural': 'Препараты',
                'db_table': 'ssr_inDb_drug',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DrugInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ampoule_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Объём ампулы (мл)')),
                ('infusion_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Скорость введения (мг/кг/час)')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='stocks.drug', verbose_name='Препарат')),
            ],
            options={
                'verbose_name': 'Препарат в заявке',
                'verbose_name_plural': 'Препараты в заявках',
                'db_table': 'ssr_inDb_druginorder',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=150, verbose_name='Создатель (username)')),
                ('moderator', models.CharField(blank=True, max_length=150, null=True, verbose_name='Модератор (username)')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('DELETED', 'Удалён'), ('FORMED', 'Сформирован'), ('COMPLETED', 'Завершён'), ('REJECTED', 'Отклонён')], default='DRAFT', max_length=10, verbose_name='Статус')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('formation_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата формирования')),
                ('completion_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('ampoules_count', models.IntegerField(blank=True, null=True, verbose_name='Количество ампул')),
                ('solvent_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Объём растворителя (мл)')),
                ('patient_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Масса пациента (кг)')),
                ('drugs', models.ManyToManyField(through='stocks.DrugInOrder', to='stocks.drug', verbose_name='Препараты')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'ssr_inDb_order',
                'ordering': ['-creation_datetime'],
            },
        ),
        migrations.AddField(
            model_name='druginorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='stocks.order', verbose_name='Заявка'),
        ),
        migrations.AlterUniqueTogether(
            name='druginorder',
            unique_together={('order', 'drug')},
        ),
        migrations.RunPython(restore_from_backup, migrations.RunPython.noop),
    ]
