# Generated by Django 5.2.7 on 2025-11-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='druginorder',
            name='drug_rate',
        ),
        migrations.AlterField(
            model_name='druginorder',
            name='infusion_speed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Скорость введения (мг/кг/час)'),
        ),
    ]
