# Generated by Django 5.2.7 on 2025-12-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_populate_descriptions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drug',
            options={'ordering': ['id'], 'verbose_name': 'Препарат', 'verbose_name_plural': 'Препараты'},
        ),
        migrations.AddField(
            model_name='druginorder',
            name='async_calculation_result',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Результат асинхронного расчета'),
        ),
    ]
