# Generated by Django 5.2.7 on 2025-10-21 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_order_formation_datetime'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='drug',
            table='ssr_inDb_drug',
        ),
        migrations.AlterModelTable(
            name='druginorder',
            table='ssr_inDb_druginorder',
        ),
        migrations.AlterModelTable(
            name='order',
            table='ssr_inDb_order',
        ),
    ]
